#TODO: take OUTPUT_IMAGE and EXPORT_PATH from common_vars.sh 

- name: Transfer and load Docker image via SSH
  hosts: remote
  become: yes
  serial: 0  # Run one machine at a time
  tasks:

    - name: Copy Docker image to remote machine
      ansible.builtin.copy:
        src: "~/docker/uvdar_workspacel:1.0.1.tar.gz"
        dest: "/tmp/uvdar_workspacel:1.0.1.tar.gz"
        mode: '0644'

    - name: Load Docker image on remote machine
      ansible.builtin.shell: docker load -i /tmp/rbl_controller_3d-test_image:1.0.0.tar.gz
      register: docker_load_output

    - name: Show Docker load output
      ansible.builtin.debug:
        msg: "{{ docker_load_output.stdout }}"



